using System.Collections.Generic;
using System.ComponentModel;

namespace SQLBasic_net;

public class LocalizationManager : INotifyPropertyChanged
{
    public static readonly LocalizationManager Instance = new();

    private string _lang = "ja";

    public string CurrentLanguage => _lang;

    private static readonly Dictionary<string, Dictionary<string, string>> _res = new()
    {
        ["ja"] = new()
        {
            // Toolbar
            ["Btn_Execute_Text"]  = " 実行 (F5)",
            ["Btn_New"]           = "📄 新規 (F4)",
            ["Btn_Open"]          = "📂 開く (Ctrl+O)",
            ["Btn_Save"]          = "💾 保存 (Ctrl+S)",
            ["Btn_Export"]        = "📤 データ保存 (Ctrl+L)",
            ["Btn_Color"]         = "🎨 カラー (Alt+C)",
            ["Lbl_Font"]          = "フォント",
            ["Btn_Format"]        = "整形 (Alt+F)",
            ["Btn_Comment"]       = "コメント (Ctrl+K)",
            ["Btn_Uncomment"]     = "コメント解除 (Shift+Ctrl+K)",
            ["Lbl_Language"]      = "言語",
            // Panel
            ["Lbl_Results"]       = "結果一覧",
            ["Lbl_Tables"]        = "テーブル一覧",
            ["Btn_ConnectDb"]     = "他のDBに接続する",
            // Status bar
            ["Lbl_Count"]         = "件数:",
            ["Lbl_CountUnit"]     = "件",
            ["Lbl_Message"]       = "メッセージ:",
            // Column headers
            ["Col_ColumnName"]    = "列名",
            ["Col_DataType"]      = "型",
            ["Col_Nullable"]      = "NULL許可",
            // Execution messages
            ["Msg_SelectHit"]     = "{0} 件のデータがヒットしました",
            ["Msg_InsertDone"]    = "{0} 件のデータを入力しました",
            ["Msg_UpdateDone"]    = "{0} 件のデータを更新しました",
            ["Msg_DeleteDone"]    = "{0} 件を削除しました",
            ["Msg_CreateDone"]    = "{0} {1} を作成しました",
            ["Msg_DropDone"]      = "{0} {1} を削除しました",
            ["Msg_NoExportData"]  = "エクスポートできるデータがありません。",
            ["Msg_SaveDone"]      = "保存しました: {0}",
            ["Msg_OpenError"]     = "ファイルを開く際にエラーが発生しました。\n{0}",
            ["Msg_SaveError"]     = "ファイル保存中にエラーが発生しました。\n{0}",
            ["Msg_ExportDone"]    = "CSVとしてエクスポートしました: {0}",
            ["Msg_ExportError"]   = "CSVエクスポート中にエラーが発生しました。\n{0}",
            // DDL object types
            ["Obj_Default"]       = "オブジェクト",
            ["Obj_Table"]         = "テーブル",
            ["Obj_Index"]         = "インデックス",
            ["Obj_UniqueIndex"]   = "ユニークインデックス",
            ["Obj_View"]          = "ビュー",
            ["Obj_Trigger"]       = "トリガー",
            // File dialogs
            ["Dlg_OpenSqlTitle"]  = "SQL ファイルを開く",
            ["Dlg_OpenSqlFilter"] = "SQL ファイル (*.sql)|*.sql|テキスト ファイル (*.txt)|*.txt|すべてのファイル (*.*)|*.*",
            ["Dlg_SaveSqlTitle"]  = "SQL ファイルの保存",
            ["Dlg_SaveSqlFilter"] = "SQL ファイル (*.sql)|*.sql|テキスト ファイル (*.txt)|*.txt|すべてのファイル (*.*)|*.*",
            ["Dlg_SaveCsvTitle"]  = "CSVファイルの保存",
            ["Dlg_SaveCsvFilter"] = "CSVファイル (*.csv)|*.csv|すべてのファイル (*.*)|*.*",
            ["Dlg_OpenDbTitle"]   = "SQLite の DB ファイルを開く",
            ["Dlg_OpenDbFilter"]  = "SQLite DB ファイル (*.db)|*.db|すべてのファイル (*.*)|*.*",
            // Completion headers
            ["Comp_TableHeader"]  = "候補テーブル",
            ["Comp_ColumnHeader"] = "候補カラム",
            ["Comp_KeywordHeader"]= "候補",
        },
        ["en"] = new()
        {
            ["Btn_Execute_Text"]  = " Execute (F5)",
            ["Btn_New"]           = "📄 New (F4)",
            ["Btn_Open"]          = "📂 Open (Ctrl+O)",
            ["Btn_Save"]          = "💾 Save (Ctrl+S)",
            ["Btn_Export"]        = "📤 Export (Ctrl+L)",
            ["Btn_Color"]         = "🎨 Color (Alt+C)",
            ["Lbl_Font"]          = "Font",
            ["Btn_Format"]        = "Format (Alt+F)",
            ["Btn_Comment"]       = "Comment (Ctrl+K)",
            ["Btn_Uncomment"]     = "Uncomment (Shift+Ctrl+K)",
            ["Lbl_Language"]      = "Language",
            ["Lbl_Results"]       = "Results",
            ["Lbl_Tables"]        = "Tables",
            ["Btn_ConnectDb"]     = "Connect to another DB",
            ["Lbl_Count"]         = "Count:",
            ["Lbl_CountUnit"]     = "",
            ["Lbl_Message"]       = "Message:",
            ["Col_ColumnName"]    = "Column",
            ["Col_DataType"]      = "Type",
            ["Col_Nullable"]      = "Nullable",
            ["Msg_SelectHit"]     = "{0} row(s) returned",
            ["Msg_InsertDone"]    = "{0} row(s) inserted",
            ["Msg_UpdateDone"]    = "{0} row(s) updated",
            ["Msg_DeleteDone"]    = "{0} row(s) deleted",
            ["Msg_CreateDone"]    = "{0} {1} created",
            ["Msg_DropDone"]      = "{0} {1} dropped",
            ["Msg_NoExportData"]  = "No data to export.",
            ["Msg_SaveDone"]      = "Saved: {0}",
            ["Msg_OpenError"]     = "Error opening file.\n{0}",
            ["Msg_SaveError"]     = "Error saving file.\n{0}",
            ["Msg_ExportDone"]    = "Exported as CSV: {0}",
            ["Msg_ExportError"]   = "Error during CSV export.\n{0}",
            ["Obj_Default"]       = "Object",
            ["Obj_Table"]         = "Table",
            ["Obj_Index"]         = "Index",
            ["Obj_UniqueIndex"]   = "Unique Index",
            ["Obj_View"]          = "View",
            ["Obj_Trigger"]       = "Trigger",
            ["Dlg_OpenSqlTitle"]  = "Open SQL File",
            ["Dlg_OpenSqlFilter"] = "SQL files (*.sql)|*.sql|Text files (*.txt)|*.txt|All files (*.*)|*.*",
            ["Dlg_SaveSqlTitle"]  = "Save SQL File",
            ["Dlg_SaveSqlFilter"] = "SQL files (*.sql)|*.sql|Text files (*.txt)|*.txt|All files (*.*)|*.*",
            ["Dlg_SaveCsvTitle"]  = "Save CSV File",
            ["Dlg_SaveCsvFilter"] = "CSV files (*.csv)|*.csv|All files (*.*)|*.*",
            ["Dlg_OpenDbTitle"]   = "Open SQLite DB File",
            ["Dlg_OpenDbFilter"]  = "SQLite DB files (*.db)|*.db|All files (*.*)|*.*",
            ["Comp_TableHeader"]  = "Tables",
            ["Comp_ColumnHeader"] = "Columns",
            ["Comp_KeywordHeader"]= "Keywords",
        },
        ["zh-CN"] = new()
        {
            ["Btn_Execute_Text"]  = " 执行 (F5)",
            ["Btn_New"]           = "📄 新建 (F4)",
            ["Btn_Open"]          = "📂 打开 (Ctrl+O)",
            ["Btn_Save"]          = "💾 保存 (Ctrl+S)",
            ["Btn_Export"]        = "📤 导出 (Ctrl+L)",
            ["Btn_Color"]         = "🎨 颜色 (Alt+C)",
            ["Lbl_Font"]          = "字体",
            ["Btn_Format"]        = "格式化 (Alt+F)",
            ["Btn_Comment"]       = "注释 (Ctrl+K)",
            ["Btn_Uncomment"]     = "取消注释 (Shift+Ctrl+K)",
            ["Lbl_Language"]      = "语言",
            ["Lbl_Results"]       = "查询结果",
            ["Lbl_Tables"]        = "表列表",
            ["Btn_ConnectDb"]     = "连接其他数据库",
            ["Lbl_Count"]         = "行数：",
            ["Lbl_CountUnit"]     = "条",
            ["Lbl_Message"]       = "消息：",
            ["Col_ColumnName"]    = "列名",
            ["Col_DataType"]      = "类型",
            ["Col_Nullable"]      = "允许NULL",
            ["Msg_SelectHit"]     = "查询到 {0} 条记录",
            ["Msg_InsertDone"]    = "已插入 {0} 条记录",
            ["Msg_UpdateDone"]    = "已更新 {0} 条记录",
            ["Msg_DeleteDone"]    = "已删除 {0} 条记录",
            ["Msg_CreateDone"]    = "已创建 {0} {1}",
            ["Msg_DropDone"]      = "已删除 {0} {1}",
            ["Msg_NoExportData"]  = "没有可导出的数据。",
            ["Msg_SaveDone"]      = "已保存：{0}",
            ["Msg_OpenError"]     = "打开文件时出错。\n{0}",
            ["Msg_SaveError"]     = "保存文件时出错。\n{0}",
            ["Msg_ExportDone"]    = "已导出为CSV：{0}",
            ["Msg_ExportError"]   = "导出CSV时出错。\n{0}",
            ["Obj_Default"]       = "对象",
            ["Obj_Table"]         = "表",
            ["Obj_Index"]         = "索引",
            ["Obj_UniqueIndex"]   = "唯一索引",
            ["Obj_View"]          = "视图",
            ["Obj_Trigger"]       = "触发器",
            ["Dlg_OpenSqlTitle"]  = "打开SQL文件",
            ["Dlg_OpenSqlFilter"] = "SQL文件 (*.sql)|*.sql|文本文件 (*.txt)|*.txt|所有文件 (*.*)|*.*",
            ["Dlg_SaveSqlTitle"]  = "保存SQL文件",
            ["Dlg_SaveSqlFilter"] = "SQL文件 (*.sql)|*.sql|文本文件 (*.txt)|*.txt|所有文件 (*.*)|*.*",
            ["Dlg_SaveCsvTitle"]  = "保存CSV文件",
            ["Dlg_SaveCsvFilter"] = "CSV文件 (*.csv)|*.csv|所有文件 (*.*)|*.*",
            ["Dlg_OpenDbTitle"]   = "打开SQLite数据库文件",
            ["Dlg_OpenDbFilter"]  = "SQLite数据库文件 (*.db)|*.db|所有文件 (*.*)|*.*",
            ["Comp_TableHeader"]  = "候选表",
            ["Comp_ColumnHeader"] = "候选列",
            ["Comp_KeywordHeader"]= "候选",
        },
        ["es"] = new()
        {
            ["Btn_Execute_Text"]  = " Ejecutar (F5)",
            ["Btn_New"]           = "📄 Nuevo (F4)",
            ["Btn_Open"]          = "📂 Abrir (Ctrl+O)",
            ["Btn_Save"]          = "💾 Guardar (Ctrl+S)",
            ["Btn_Export"]        = "📤 Exportar (Ctrl+L)",
            ["Btn_Color"]         = "🎨 Color (Alt+C)",
            ["Lbl_Font"]          = "Fuente",
            ["Btn_Format"]        = "Formato (Alt+F)",
            ["Btn_Comment"]       = "Comentar (Ctrl+K)",
            ["Btn_Uncomment"]     = "Descomentar (Shift+Ctrl+K)",
            ["Lbl_Language"]      = "Idioma",
            ["Lbl_Results"]       = "Resultados",
            ["Lbl_Tables"]        = "Tablas",
            ["Btn_ConnectDb"]     = "Conectar a otra BD",
            ["Lbl_Count"]         = "Filas:",
            ["Lbl_CountUnit"]     = "",
            ["Lbl_Message"]       = "Mensaje:",
            ["Col_ColumnName"]    = "Columna",
            ["Col_DataType"]      = "Tipo",
            ["Col_Nullable"]      = "Nulo",
            ["Msg_SelectHit"]     = "{0} fila(s) encontrada(s)",
            ["Msg_InsertDone"]    = "{0} fila(s) insertada(s)",
            ["Msg_UpdateDone"]    = "{0} fila(s) actualizada(s)",
            ["Msg_DeleteDone"]    = "{0} fila(s) eliminada(s)",
            ["Msg_CreateDone"]    = "{0} {1} creado",
            ["Msg_DropDone"]      = "{0} {1} eliminado",
            ["Msg_NoExportData"]  = "No hay datos para exportar.",
            ["Msg_SaveDone"]      = "Guardado: {0}",
            ["Msg_OpenError"]     = "Error al abrir archivo.\n{0}",
            ["Msg_SaveError"]     = "Error al guardar archivo.\n{0}",
            ["Msg_ExportDone"]    = "Exportado como CSV: {0}",
            ["Msg_ExportError"]   = "Error al exportar CSV.\n{0}",
            ["Obj_Default"]       = "Objeto",
            ["Obj_Table"]         = "Tabla",
            ["Obj_Index"]         = "Índice",
            ["Obj_UniqueIndex"]   = "Índice único",
            ["Obj_View"]          = "Vista",
            ["Obj_Trigger"]       = "Disparador",
            ["Dlg_OpenSqlTitle"]  = "Abrir archivo SQL",
            ["Dlg_OpenSqlFilter"] = "Archivos SQL (*.sql)|*.sql|Archivos de texto (*.txt)|*.txt|Todos los archivos (*.*)|*.*",
            ["Dlg_SaveSqlTitle"]  = "Guardar archivo SQL",
            ["Dlg_SaveSqlFilter"] = "Archivos SQL (*.sql)|*.sql|Archivos de texto (*.txt)|*.txt|Todos los archivos (*.*)|*.*",
            ["Dlg_SaveCsvTitle"]  = "Guardar archivo CSV",
            ["Dlg_SaveCsvFilter"] = "Archivos CSV (*.csv)|*.csv|Todos los archivos (*.*)|*.*",
            ["Dlg_OpenDbTitle"]   = "Abrir archivo SQLite DB",
            ["Dlg_OpenDbFilter"]  = "Archivos SQLite DB (*.db)|*.db|Todos los archivos (*.*)|*.*",
            ["Comp_TableHeader"]  = "Tablas",
            ["Comp_ColumnHeader"] = "Columnas",
            ["Comp_KeywordHeader"]= "Palabras clave",
        },
    };

    public string this[string key] =>
        _res.TryGetValue(_lang, out var d) && d.TryGetValue(key, out var v) ? v : key;

    public void SetLanguage(string lang)
    {
        if (_lang == lang) return;
        _lang = lang;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
    }

    public event PropertyChangedEventHandler? PropertyChanged;
}
